#!/bin/sh -e




castty_kill() {
    F="/var/run/user/$(id -u)/castty.pid"
    if [ -e "${F}" ]; then
        xargs -n 1 kill < ${F} && rm "${F}"
    fi
}


castty_run() {
    export CASTTY_COMMAND

    exec sbcl --noinform --disable-debugger --disable-ldb --lose-on-corruption --noprint \
         <<EOF
         (require 'castty)
         (castty::driver)
EOF
}



CASTTY_COMMAND="$1"
if [ -z "${CASTTY_COMMAND}" ] ; then
   >&2 echo "ERROR: No command given"
   exit 1
fi

case "${CASTTY_COMMAND}" in
    kill)
        castty_kill
        ;;
    *)
        castty_run
        ;;
esac
